### ISSUE TITLE
[Defect]

### ISSUE THREAD

**Issue by Amira1502** [near/wallet-selector#1415]
**Describe the bug**

After updating @near-wallet-selector to version 9.4.0, running npm run dev throws the following error:
```
Error: No "exports" main defined in 
C:\Users\nasri\guest-book-examples\frontend\node_modules\@near-wallet-selector\meteor-wallet\node_modules\@meteorwallet\sdk\package.json
```

**Steps To Reproduce**å

1. Clone the repo guest-book-examples
2. Update @near-wallet-selector to 9.4.0
3. . Run npm install
4.  Start the dev server with npm run dev

_Error description_
The build fails immediately with an exports/main resolution error coming from @meteorwallet/sdk, which is a dependency of @near-wallet-selector/meteor-wallet.

**Expected behavior**
The project should start normally without errors after updating Wallet Selector.

**Screenshots**
<img width="1139" height="378" alt="Image" src="https://github.com/user-attachments/assets/b2b51a8d-2042-4d44-ab1a-fcb8ca3e7802" />

**Desktop**: 

- OS: Windows 10
- Browser: Chrome
- Browser Version: 139

**Additional Context**
This only appeared after upgrading to 9.4.0. It looks like @meteorwallet/sdk may be missing a proper "exports" or "main" field in its package.json.

**Comment by ahnafalfariza** [comment]
thanks for reporting this! seems its missing the main field
 

@lostpebble could you please add the field `"main": "./dist/index.js"` to the package.json of `@meteor/sdk`? once that’s in place, I can bump the version in Wallet Selector

**Comment by ahnafalfariza** [comment]
thanks for reporting this! it looks like the main field is indeed missing from the package.json

<img width="775" height="748" alt="Image" src="https://github.com/user-attachments/assets/610812f3-b56f-4571-b04d-1d702624619a" />



@lostpebble could you please add the field `"main": "./dist/index.js"` to the package.json of `@meteor/sdk`? once that’s in place, I can bump the sdk version in Wallet Selector

**Comment by lostpebble** [comment]
Hi @ahnafalfariza I've just published 1.0.23 with the exported `main` field- sorry about that, `"exports"` should generally be sufficient according to the [spec](https://nodejs.org/api/packages.html#main-entry-point-export), but it appears some build systems still require `"main"`.

Thanks for the report @Amira1502.

**Comment by ahnafalfariza** [comment]
@lostpebble yeah, I wasn't aware of that. thanks for the quick response!

**Comment by ahnafalfariza** [comment]
@Amira1502 we just released 9.5.0, does the issue still persist?

**Comment by Amira1502** [comment]
@ahnafalfariza  Yes, unfortunately. I deleted `node_modules` and reinstalled everything, but I’m still getting:

<img width="1505" height="574" alt="Image" src="https://github.com/user-attachments/assets/aecc4791-9f1e-4918-bf7b-849a76c1d525" />

**Comment by lostpebble** [comment]
@ahnafalfariza I've just published `1.0.24`- I've verified it using this tool: https://arethetypeswrong.github.io/?p=%40meteorwallet%2Fsdk%401.0.24

Hopefully that should solve the commonjs issue now.
