### ISSUE TITLE
UI issues on establishing the wallet-selector

### ISSUE THREAD

**Issue by hcho112** [near/wallet-selector#374]
**Describe the bug**

1.  Unlike the example in `example/react`, I had to manually import wallet icon url and update on `setupXXX` function all. (or if I don't import them manually, I will get result as below)

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/6027014/182734066-30de0af2-354b-4a4c-a91a-6eb2ce28e9f1.png)</span>](https://user-images.githubusercontent.com/6027014/182734066-30de0af2-354b-4a4c-a91a-6eb2ce28e9f1.png)

1.  Unlike the example in `examples/react` I had to manually import `@near-wallet-selector/modal-ui/styles.css` or modal UI looks strange as below.

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/6027014/182736517-d33db81f-402d-425b-b4ef-2a48ebe78b25.png)</span>](https://user-images.githubusercontent.com/6027014/182736517-d33db81f-402d-425b-b4ef-2a48ebe78b25.png)

1.  Invalid wallet icon alignment [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/6027014/182735209-5a28506b-70e0-443e-b113-713bc997ba83.png)</span>](https://user-images.githubusercontent.com/6027014/182735209-5a28506b-70e0-443e-b113-713bc997ba83.png)

**To Reproduce** Steps to reproduce the behavior:

1.  `git clone git@github.com:near/ui.multisafe.git`
2.  checkout to `revert-154-revert-134-MUL-10`
3.  run `yarn && yarn start`

**Expected behavior** Bug1\. I shouldn't had to manually import and insert `iconUrl` to setup functions. If I don't pass anything, it should automatically fallback to default image Bug2\. I shouldn't had to manually import css file. (I think this is a bug but even if this is intentional, it was missing from readme) Bug3\. It should render just as same as `examples/react`

**Screenshots** If applicable, add screenshots to help explain your problem.

**Device (please complete the following information):**

*   OS: iOS
*   Browser Chrome
*   Version 5.0.1

**Additional context** Add any other context about the problem here.

**Comment by kujtimprenkuSQA** [comment]
Hey, @hcho112 thank you for raising this issue.

For: Bug1. 
- At the moment we expose icons under `/assets` folder for each wallet, to show icons a developer can either copy these assets through webpack or any other builder to their public folder or just provide the `iconUrl` to the setup function. There's documentation on the readme of each wallet. This is the default behavior of NX when handling assets but we will look into improving it as you suggested here, so the developer does not need to provide `iconUrl` unless they want to change the icon.

For: Bug2.
- This is not a Bug, the css needs to be imported this has been done to give developers more flexibility if they wish to override some of the css variables or styles there's documentation here: https://github.com/near/wallet-selector/tree/main/packages/modal-ui

For: Bug3
- Not sure if this is a bug or just confusion since there's documentation in `modal-ui` package.  But just to avoid confusion in the future we will add a readme on each example and explain it there too.

For the invalid wallet icon alignment, you might have css that overrides styling for images.

**Comment by hcho112** [comment]
@kujtimprenkuSQA Thank you for quick feedback, really appreciated 👍 
For the Bug3, I did further investigation to see if the css issue is coming from `ui.multisafe`. Unfortunately the issue was still originated from `wallet-selector` as below:

A. Screenshot from example with showing css rule for `.nws-modal-wrapper .spinner img` as:
![image](https://user-images.githubusercontent.com/6027014/182960365-be325975-4788-4a26-b347-05ef12d16c72.png)

B. Screenshot from example with html structure:
![image](https://user-images.githubusercontent.com/6027014/182960529-e9a695f8-9b7a-40cc-aa6c-ccffc1ef111c.png)

C. CSS rule expression on point B:
```
.nws-modal-wrapper .spinner .icon {
  width: calc(var(--size) / 1.2);
  height: calc(var(--size) / 1.2);
  border: 1px solid rgba(0, 0, 0, 0.05);
  border-radius: 50%;
  box-shadow: rgb(0 0 0 / 5%) 0 10px 20px 0;
}
.nws-modal-wrapper .spinner img {
  width: 100%;
  height: auto;
  padding: 20px;
}
```
So what's happening is that `img` element is applied with `.nws-modal-wrapper .spinner .icon` instead of `.nws-modal-wrapper .spinner img ` in example react page. 

Where as, when we import `wallet-selector` as a package and do the same steps:
![image](https://user-images.githubusercontent.com/6027014/182961140-d83fae64-0827-4f4a-b5e1-5aedc723b2c6.png)
Notice that html structure has been changed, and css rule applied to `img` element is also different. (notice that now it is applying `.nws-modal-wrapper .spinner img ` instead of `.nws-modal-wrapper .spinner .icon`

So it is not the matter of `box-sizing` issue, instead it is more coming from inconsistent outcome from what's shown on examples vs what is actually returning if we import from `wallet-selector` repo. 

I was able to hack the css rule by creating custom css rule as below:
```
.nws-modal-wrapper .spinner img {
  width: calc(var(--size) / 1.2);
  height: calc(var(--size) / 1.2);
  border: 1px solid rgba(0, 0, 0, 0.05);
  border-radius: 50%;
  box-shadow: rgb(0 0 0 / 5%) 0 10px 20px 0;
  padding: 0;
}
```
<img width="1768" alt="image" src="https://user-images.githubusercontent.com/6027014/182961781-37034f46-12f2-49b2-bb9a-0caa6fb7dfd7.png">


Regardless I believe this is still an issue and would be appreciated if the team look into it further. Happy to assist.

**Comment by kujtimprenkuSQA** [comment]
Hey, @hcho112 

I pulled down your latest changes from your branch `revert-154-revert-134-MUL-10` as far as I can understand the markup is the same with what we have already published in our `main` branch.

When you switch to `main` branch of `wallet-selector` can you make sure to do a `git pull` and see if there are changes in the remote?
I could not reproduce the inconsistency for the markup mentioned above.
Here is the published version of `main` branch : https://near.github.io/wallet-selector/

I tried editing this [file](https://github.com/near/ui.multisafe/blob/revert-154-revert-134-MUL-10/src/ui/providers/WalletSelectorProvider/custom.css) locally with this css rule below, In my case, the image is aligned correctly this way

```css
.nws-modal-wrapper .spinner img {
    box-sizing: border-box;
}
```

Since I could not reproduce the inconsistency of the markup between the example we have in `main` and the implementation you have I would like to think it's just a css problem. If you know how to reproduce it please let me know I would like to make this fix too. Thanks.

**Comment by hcho112** [comment]
Hello, @kujtimprenkuSQA 
Again, thank you for quick response.

Just follow up with your response, when I tested and report this issue, I was at `main` branch AND previously was on `v4.1.1` and then pull latest which was at `v5.0.2` and it was still showing inconsistent html tree. (difference between whats showing on react example and whats on source code was different) After checking with your feedback and further investigation, I found out that if I was on older version and pull latest version (release) **I actually need to rebuild in order to apply latest changes on react example.** 

I assumed that it will apply latest changes to react example straightaway, but after seeing the reference where react example code is referencing to, it actually fetch from `dist` directory. (So after I ran the `yarn run build:all` it did update `dist` directory with latest changes. 

And when I reached to this point, previous feedback started to make sense and applying suggested changes fixed the problem. Moving forward, only thing that I could think of is to run make update on `serve:react` command as:
`"serve:react": "yarn build:all && nx serve react"` in a sense that react example is guaranteed to build and run against latest source code? (Happy to make PR if this is a good approach)

Thank you for the assistance so far!

**Comment by kujtimprenkuSQA** [comment]
Hey, @hcho112

The `modal-ui` package needs to point to the `dist` folder because we have an Angular example too and and trying to import the `jsx` files directly to an Angular example would fail that's why whenever the source code changes in `modal-ui` this package needs a re-build.

I do not think it is necessary to combine `build` and `serve` command because it's only the modal-ui package that requires re-build. For other packages if you build them once and serve the react example and then if you change the source code in any of the packages the changes will reflect immediately.

We will be making that fix about the css rule though.

Thanks for your feedback.
